FROM node:18.12.1-alpine AS build

WORKDIR /app
COPY package.json package-lock.json ./

COPY . .
RUN npm install
RUN npm run build


FROM nginx:1.23.2-alpine

RUN apk --no-cache add vim

RUN rm /etc/nginx/conf.d/default.conf

COPY ./.nginx/dev.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]