version: "3.9"
services:
  # Django
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: 930849404806.dkr.ecr.ap-northeast-2.amazonaws.com/todo:backend
    volumes:
      - ./backend:/app/backend
      - static_volume:/app/backend/django_static
    env_file:
      - ./backend/todo_project/.env
    ports:
      - 8000:8000
    depends_on:
      - redis

  # Redis
  redis:
    image: "redis:alpine"

  # React-nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: 930849404806.dkr.ecr.ap-northeast-2.amazonaws.com/todo:frontend
    container_name: frontend
    volumes:
      - static_volume:/app/backend/django_static
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  static_volume:
