version: "3"
services:
  # Django
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend
      - staticfiles:/app/backend/staticfiles
    env_file:
      - ./backend/todo_project/.env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 8000:8000
  # React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend:/app/frontend/build

  # Nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - staticfiles:/staticfiles
      - frontend:/var/www/frontend
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  # Worker
  # this image does not copy requirements.txt from ./backend/ ???
  # how to reduce image size
  celery_worker:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: celery -A todo_project worker -l info
    volumes:
      - ./backend:/app/backend
    depends_on:
      - redis
      - db
  # Beat
  celery_beat:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: celery -A todo_project beat -l INFO
    volumes:
      - ./backend:/app/backend
    depends_on:
      - redis
      - db

volumes:
  staticfiles:
  frontend:
