version: "3.9"
services:
  # Worker
  # this image does not copy requirements.txt from ./backend/ ???
  # how to reduce image size
  celery_worker:
    image: userksv/mysite-celery_worker
    build:
      context: .
    command: python -m celery -A todo_project worker -l info
    volumes:
      - ./backend:/app/backend
    depends_on:
      - redis
      - db
  # Beat
  celery_beat:
    image: userksv/mysite-celery_beat
    build:
      context: .
    command: celery -A todo_project beat -l INFO
    volumes:
      - ./backend:/app/backend
    depends_on:
      - redis
      - db

  # Redis
  redis:
    image: "redis:alpine"

  # PostgreSQL
  db:
    image: userksv/mysite-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/

  # React
  frontend:
    image: userksv/mysite-frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend

  # Django
  backend:
    image: userksv/mysite-backend
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    depends_on:
      - redis
      - db
