version: "3.9"
services:
  # Django
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: /start-django
    volumes:
      - ./backend:/app/backend
      - static_volume:/app/backend/staticfiles
    environment:
      - ENV=dev
    env_file:
      - ./backend/todo_project/.env.dev
    expose:
      - 8000
    depends_on:
      - redis
      - db

  # Redis
  redis:
    image: "redis:alpine"
  # PSQL
  db:
    image: postgres:15
    volumes:
      - ps_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  # React-nginx
  frontend:
    container_name: react-nginx
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - static_volume:/app/backend/staticfiles
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - backend

    # Worker
  # this image does not copy requirements.txt from ./backend/ ???
  # how to reduce image size
  # celery_worker:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #   command: /start-worker
  #   volumes:
  #     - ./backend:/app/backend
  #   env_file:
  #     - ./backend/todo_project/.env.dev
  #   depends_on:
  #     - redis
  # # Beat
  # celery_beat:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #   command: /start-beat
  #   volumes:
  #     - ./backend:/app/backend
  #   env_file:
  #     - ./backend/todo_project/.env.dev
  #   depends_on:
  #     - redis
volumes:
  static_volume:
  ps_data:
