version: "3.9"
services:
  # Django
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: python manage.py runserver
    environment:
      - ENV=dev
    volumes:
      - ./backend:/app/backend
      - static_volume:/staticfiles
    env_file:
      - ./backend/todo_project/.env.dev
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db

  # Redis
  redis:
    image: "redis:alpine"

  # PostgreSQL
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/

  # React-nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app/frontend
      - /app/node_modules
    ports:
      - 80:80
    depends_on:
      - backend

  # Worker
  # this image does not copy requirements.txt from ./backend/ ???
  # how to reduce image size
  celery_worker:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    command: python -m celery -A todo_project worker -l info
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/todo_project/.env.dev
    depends_on:
      - redis
      - db
  # Beat
  celery_beat:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    command: celery -A todo_project beat -l INFO
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/todo_project/.env.dev
    depends_on:
      - redis
      - db
volumes:
  static_volume:
